### ISSUE TITLE
Installation problems on Windows 7 Professional x64 SP1

### ISSUE THREAD

**Issue by SeedyThreeSixty** [kirb/LegacyUpdate#109]
When I try to install Legacy Update on Windows 7, the installer only gives me the option to update root certificates, and when I try to launch LU itself, it says Legacy Update isn't installed or needs to be updated. I'm installing Legacy Update 1.6.2.

**Comment by Vichingo455** [comment]
That's normal since Windows 7 can still update itself from Microsoft Update without having to use a WSUS Server

**Comment by kirb** [comment]
Implemented in [Legacy Update 1.7](https://github.com/kirb/LegacyUpdate/discussions/169). Thanks for the inspiration to add this feature back.
