### ISSUE TITLE
Error on Windows 2003 Server SP2

### ISSUE THREAD

**Issue by Arkaines** [kirb/LegacyUpdate#11]
Hello, I have a bug when I try to update a Windows 2003 Server SP2

## Expected Behavior
Working update ;)

## Current Behavior
Update won't work.

## Steps to Reproduce
1. Install Legacy Update 1.2 = OK (Except certificate, i've got an error)
2. Launch Legacy Update = OK
3. I've Got this error
`The Windows Update service encountered an error.

0x8024402F (-2145107921): External cab file processing completed with some errors.

Visit the homepage to confirm that you have completed all prerequisites for using Legacy Update. 
The Windows Update Frequently Asked Questions may also be useful. 
 
`
## Context (Environment)
Windows Server 2003 SP2

Could you please help me?

Thanks
![Error_LegacyUpdate](https://user-images.githubusercontent.com/95678985/201634349-0e2ccdbd-5026-4208-8b81-b90aa8b6616c.png)

**Comment by Arkaines** [comment]
There is an old parameter who block windows update website...

But now i've this error

0x80244018 (-2145107944): HTTP 403 - server understood the request, but declined to fulfill it.

**Comment by makuhlmann** [comment]
> (Except certificate, i've got an error)

That could be the cause. Cabs are signed by Microsoft and if the corresponding certificates are missing, it's can run into an error.
Run the Legacyupdate installer again, it will try again to update the root certificates.
If the installation of the certificates keeps failing, you can try to install this one instead: http://i430vx.net/files/wsusstuff/NT5x/rootsupd.exe

**Comment by Arkaines** [comment]
Thank you, i think Zscaller block the certificate when i try to install it, i have a 403 “Access Forbidden” .
Can you give me with address is used to download certificate, please?

**Comment by Arkaines** [comment]
Hello,

I close the issue our Zcaler proxy block the rules to windows update due to our MECM architecture..

Thank you for your help :)
