### ISSUE TITLE
Spending a lot of time to check SSL on China mainland

### ISSUE THREAD

**Issue by ljlofficial** [kirb/LegacyUpdate#116]
When I setup LegacyUpdate on China mainland. I always wait for the setup program to check SSL. And I spent  2h  checking it. Could you help China mainland user spend a little time to check SSL?

**Comment by kirb** [comment]
Fixed in [1.7](https://github.com/kirb/LegacyUpdate/discussions/169) - SSL check should succeed or fail immediately now rather than taking forever to time out.
