### ISSUE TITLE
Can't Update Windows, Error 0x8024400A

### ISSUE THREAD

**Issue by Polytelus** [kirb/LegacyUpdate#118]
![image](https://user-images.githubusercontent.com/42881164/217352489-1eef882a-5a42-42d8-bb21-4a8ff50059ab.png)

This screen shows up every time and just makes Windows Update refuse to work. I've checked and the error presented `SOAPCLIENT_PARSE_ERROR` is also present on the website. What does it mean? Why is it occurring now? I've never had this before.

- Software: Oracle VM Virtualbox 6.1
- Also confirmed happening on:

| Platform      | Version | OS | Service Pack | Additional Info |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Virtualbox      | 6.1.38       | Windows XP Professional | Service Pack 3 | EN-US |
| QEMU (KVM)  | 7.0.0      | Windows XP Professional | Service Pack 3 | PT-BR |
| PC | Compaq Presario SR5522PT | Windows Vista | Service Pack 2 | PT-PT |
| PC | GIGABYTE GA-VM900M (FC) | Windows XP Professional | Service Pack 3 | EN-US |
| VM | ??? | Windows Vista HP x86 | Service Pack 2 | PT-PT |

- The issue does not seem to be related to the system language.
- Using a newer version of IE does not seem to solve the issue.

EDIT:
After a while, I got a new error: `80244008: Unknown error`.

**Comment by Polytelus** [comment]
I have a feeling this might be caused by the language on the system, will attempt to download an English version.

**Comment by NiPPonD3nZ0** [comment]
Well, I created my account just to post on here! Yesterday it worked, perfectly, on my Windows Vista SP2 PT-PT 32Bit installation, that I had restored my Compaq Presario SR5522PT back to factory and tried to update it with Legacy Update and went has far as to download about 200 updates and then installed a few, when I decided to shutdown the PC, installed more RAM and a new 1TB SSD and restored it again with the image factory image... Went on to try and do the same thing today, and I get this same error...

**Comment by Polytelus** [comment]
> I have a feeling this might be caused by the language on the system, will attempt to download an English version.

Nope, doesn't seem like it's the language. And according to the comment above doesn't seem like an isolated issue...

**Comment by NiPPonD3nZ0** [comment]
> After a while, I got a new error: 80244008: Unknown error.

same thing here, on a VM with a clean Windows Vista Home Premium SP2.

**Comment by kirb** [comment]
Is this fixed now? I think this is from my server running out of space the other day, which is fixed now.

**Comment by NiPPonD3nZ0** [comment]
It is! Thank you very much! It's a very good work you are doing here!

**Comment by Polytelus** [comment]
Fixed indeed! Thank you so much!
It also seems to have fixed the action bar on the main page somehow. xD
