### ISSUE TITLE
Update search results in error 80244008

### ISSUE THREAD

**Issue by fiasn** [kirb/LegacyUpdate#119]
Windows XP Professional x86 SP3, Dell Inspiron 5100. i was able to install updates initially but after a restart, it refuses to check. I believe the error has something to do with WSUS, but reinstalling legacy update did not fix it.

**Comment by Tillamook233** [comment]
I have also been experiencing this on my Dell Dimension 8300 with XP Professional x86 SP3. At first I thought it was because I had installed Office XP but the issue persists even after a complete reinstall of XP.

**Comment by fiasn** [comment]
seems as if the issue has resolved itself. potentially a problem on legacy update's side.

**Comment by kirb** [comment]
It most likely was because my server ran out of space. Fixed now, sorry that happened. Made some space earlier and will clean up further over the next few days so it hopefully won’t happen again.

**Comment by nononymousse** [comment]
hi ^^
i have the same issue on a VM i did a while back and i just installed Legacy Update and it got me this error. Tho i have the update pop-up in systray for updates that still work (it install them and all)
