### ISSUE TITLE
Error 80244019 when switching from a WSUS server to Legacy Update

### ISSUE THREAD

**Issue by dudefoxlive** [kirb/LegacyUpdate#12]
So helping a friend use this and it seems that it can't connect to http://legacyupdate.net/v6/ClientWebService/client.asmx. Claims that it is a DNS problem but when changing it to cloudflare and running ipconfig /flushdns nothing changes. I have no idea where to start. I have added the log if that helps.
![image](https://user-images.githubusercontent.com/50186495/201736695-3c2ea11e-b384-4e82-bd0c-e14e7c816c9a.png)
[WindowsUpdateLOG.txt](https://github.com/kirb/LegacyUpdate/files/10006002/WindowsUpdateLOG.txt)

**Comment by kirb** [comment]
Looks like it’s trying to access `http://legacyupdate.net/v6/SimpleAuthWebService/SimpleAuth.asmx` which I don’t implement, although I could look into it. Seems like maybe the update agent calls that when the machine was previously registered with a private WSUS server? (As opposed to a “public” one like Legacy Update or the Microsoft official server). I can see you had a different server address at the start of your logs so that could be the case.

**Comment by thewillwilson** [comment]
Getting the exact same error here, Server 2003 SP2, we used to have a private WSUS but that's now been decommed, how do we undo the simpleauthwebservice bit?

**Comment by kirb** [comment]
Still trying to understand how SimpleAuth works so I can have the server just transparently handle this, but you could for now:

1. Stop Automatic Updates in services.msc
2. Go to C:\\Windows and delete the SoftwareDistribution folder
3. Run regedit and go to HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate, delete TargetGroup and TargetGroupEnabled if they exist
4. Start Automatic Updates again

**Comment by theyellowpenguin** [comment]
I have the same issue, I followed those steps but now I have a totally different error, now I have "0x80072EFFE (-2147012866): Unknown Error" Not sure what to do to fix this.

**Comment by kirb** [comment]
That error means connection aborted, it can be an SSL related issue. The server hopefully shouldn't be configured to use https:// on XP/Vista/2003/2008 - try the "Check Update Server" button on the homepage to find out. SSL connection is required on Windows 7/2008 R2 and later as of a servicing stack update a few years back, so on those you'll need to use https:// *and* have the patches that enable all the current TLS ciphers installed (I don't know exactly which those are off the top of my head).

**Comment by techguy16** [comment]
TLS 1.2 and TLS 1.3 :smiley:

**Comment by kirb** [comment]
I just implemented SimpleAuthWebService, proxying the requests to Microsoft the same way the main ClientWebService does. I've seen what looks like successful responses come through so far, but would really appreciate if you could give it a try and let me know how it goes. I've apparently forgotten the password to my test WSUS server (:zany_face:) so I haven't had a chance to test it yet.

**Comment by kirb** [comment]
Going to close because I think this has been solved.
