### ISSUE TITLE
Can't install Legacy Update on Windows 7.

### ISSUE THREAD

**Issue by Zapidom** [kirb/LegacyUpdate#126]
When trying to install LegacyUpdate 1.6.2 from the Legacy Update website, it installs a couple security updates(?), signs out, signs into a new user account or something, continues installing, signs out, restarts(?), signs back into my main user account and finishes the installation. Even if I reboot, Legacy Update does not detect that it's installed. When rerunning the installer, the only option is "Update root certificates store".

**Comment by Vichingo455** [comment]
The reason behind you can't reinstall Legacy Update is because Windows 7 doesn't need it. It's able to download updates from Microsoft Update fine, so overwriting the WU server would be an useless thing

**Comment by kirb** [comment]
The option to install Legacy Update on Windows 7 - 11 has been added in [1.7](https://github.com/kirb/LegacyUpdate/discussions/169).
