### ISSUE TITLE
Installation failed could not load NSxfer.dll on Windows 2000 

### ISSUE THREAD

**Issue by witcheslive** [kirb/LegacyUpdate#131]
Trying to install Legacy Update on Windows 2000 with the 1.6.2 version:

![image](https://user-images.githubusercontent.com/42488274/221930555-c377b192-ec28-4b46-9987-a3f8dd1eaca1.png)

![image](https://user-images.githubusercontent.com/42488274/221930516-36f87360-42e6-4751-81eb-01bf848de599.png)

**Comment by witcheslive** [comment]
1.6.1 installs just fine but unfortunately does not allow legacyupdate.net's updater to work

**Comment by Vichingo455** [comment]
> Trying to install Legacy Update on Windows 2000 with the 1.6.2 version:
> 
> ![image](https://user-images.githubusercontent.com/42488274/221930555-c377b192-ec28-4b46-9987-a3f8dd1eaca1.png)
> 
> ![image](https://user-images.githubusercontent.com/42488274/221930516-36f87360-42e6-4751-81eb-01bf848de599.png)

Maybe that dll is not working on Windows 2000. Try downloading the updates manually from http://catalog.update.microsoft.com

**Comment by witcheslive** [comment]
It's something wrong with legacyupdate and win2k, because if I install that manually I get this problem instead:

![image](https://user-images.githubusercontent.com/42488274/222491066-ae3d0169-4cac-4cf9-a9d9-31760d9ccf1c.png)

![image](https://user-images.githubusercontent.com/42488274/222491156-3596a5c7-8bff-4f59-bb3c-ccc69c0891d4.png)

**Comment by Vichingo455** [comment]
I got a quick idea: Have you installed VC++ 2008 Runtime?

**Comment by renodr** [comment]
@witcheslive what CPU do you have? This sounds eerily familiar to the issue over in #154 which will get fixed in the soon-to-be released LegacyUpdate 1.7.

**Comment by kirb** [comment]
Going to close because we have the hunch that it's the SSE issue (NSxfer.dll was compiled to use SSE instructions, but the original Pentium lacks SSE), which is fixed in [1.7](https://github.com/kirb/LegacyUpdate/discussions/169). Feel free to reopen if 1.7 doesn't fix it for you.
