### ISSUE TITLE
system requirements on the home page

### ISSUE THREAD

**Issue by nononymousse** [kirb/LegacyUpdate#133]
Hi \^^
i just installed Legacy Update on a windows 2000 VM and while the website say in the banner it work with 2000, the system requirements under the "Install Legacy Update" does not and i was confuse if it will work or not 😅

i did downloaded it and it did work but will it be possible to add Windows 2000 on that system requirement list then ? 

Also the top bar say it work up to vista/server 2008, what about doing another banner ? (don't think adding the other supported OS'es will be feasable/look nice xD)

have a great day all and thanks for that amazing work 💜

**Comment by kirb** [comment]
I wonder how I missed 2000 there 🤦‍♀️ Thanks, fixed.

I do need to redo the site banner, it’s already a bit too long as-is!
