### ISSUE TITLE
Using Setup keys instead of creating a new user

### ISSUE THREAD

**Issue by Vichingo455** [kirb/LegacyUpdate#138]
I heard that creating new user has issues with non-English windows copies. As well I propose a solution: you should use the setup keys (`HKEY_LOCAL_MACHINE\SYSTEM\Setup`)
The usage is:
* `CmdLine` - The EXE file to be executed, use the current RunOnce value
* `SetupType` - Set to 2 for enable, 0 to disable
* `SetupPhase` - Set to 4 for enable, 0 to disable
* `SystemSetupInProgress` - Set to 1 for enable, 0 for disable

Unique limitation: There's no Wi-Fi support here

Hope this help.

**Comment by kirb** [comment]
We figured out this isn't really viable, because the OS puts itself in a preinstallation state with limited services running, kinda like Safe Mode. I'm also not sure if it works past XP. Seems the temp user is still the better option.
