### ISSUE TITLE
Not working on Windows Vista - 80072EFE 

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [kirb/LegacyUpdate#14]
I tried Legacy Update on a Windows Vista Home Basic x86 VM, and I got the same "80072EFE" error that normal Windows update shows. I tried installing Windows Update Agent 7.6.7600.256, however got the same error.

**Comment by kirb** [comment]
Thanks for reporting, going to close this in favor of #8 so we can track the issue in one place.
