### ISSUE TITLE
Legacy Update stops working after upgrading Windows

### ISSUE THREAD

**Issue by yotoprules** [kirb/LegacyUpdate#142]
Hi!
I had Windows Vista SP2 Enterprise.
LU worked fine.
Upgraded to 7 SP1 Enterprise. Updates weren't working. So uninstalled LegacyUpdate and when I go to re-install it, it only gives me an option for "Update root certificates store" so I cannot reinstall LegacyUpdate.
Is there a way to force it to install again?
Thanks!

**Comment by Vichingo455** [comment]
The reason behind you can't reinstall Legacy Update is because Windows 7 doesn't need it. It's able to download updates from Microsoft Update fine, so overwriting the WU server would be an useless thing

**Comment by Vichingo455** [comment]
As well you can force the Legacy Update servers by setting up a group policy (Specify Intranet Windows Update Server)

**Comment by kirb** [comment]
The option to install Legacy Update on Windows 7 - 11 has been added in [1.7](https://github.com/kirb/LegacyUpdate/discussions/169).
