### ISSUE TITLE
800A138F unknown error

### ISSUE THREAD

**Issue by HEB2021** [kirb/LegacyUpdate#148]
Legacy Update isnt installed or needs to be updated.

I installed legacy update on win2k and it succeeded but the webpage gives the error in the title as well as legacy update isnt installed or needs to be updated. this is a clean install of win2k for reference

**Comment by kocoman2** [comment]
is your automatic update in the control panel set to "OFF/Disabled".. ?  I had to set to "notify me only" then it worked.. on xp x64

**Comment by kirb** [comment]
Going to close this because a few updates have come out since this, and there were probably a bunch of server changes that could have been related. If it’s still happening for you, please open a new issue or ask on the Discord. Thanks!
