### ISSUE TITLE
80072EFE after recent commit on Windows 7 and Server 2008 R2

### ISSUE THREAD

**Issue by renodr** [kirb/LegacyUpdate#149]
While working on modifying the Legacy Update installer to install Update Rollup 4 on Windows Home Server 2011 to fix other Windows Update-related issues, I found out that Windows Server 2008 R2 and Windows 7 support was broken after commit 156d232ff1c56d28b41c2bda6d9e6c7104c553c7

I did some investigation with turning off IE Enhanced Security Configuration on Server 2008 R2, which had no impact. After looking closer at that commit, I applied KB3138612 manually and was able to use Windows Update again. That update was not superseded by KB4474419 and KB4490628 and appears to be still needed.

Note that these were fresh installs of Windows Server 2008 R2 x64 and Windows 7 x86.

Going to cook up a PR to fix this shortly
![LU Fail Windows 7](https://github.com/kirb/LegacyUpdate/assets/11901488/e5d02c24-7c40-4530-b1c3-e659609fbc35)

**Comment by renodr** [comment]
My PR works on 7, but untested on Windows Server 2008 R2 just yet. I'll do that tomorrow morning (US Time).

**Comment by kirb** [comment]
Will release the fix in 1.7.1, just merged the commit from #151.
