### ISSUE TITLE
No updates for localised Windows XP?

### ISSUE THREAD

**Issue by roytam1** [kirb/LegacyUpdate#15]
I tried to use LegacyUpdate on Chinese Traditional localised Windows XP (not MUI) and it finds no updates on this newly installed plain XP SP3. Is this normal?

**Comment by XPMilkChan** [comment]
Are you still having problems?
Roytam I am installing
Version (Traditional Chinese) (Hong Kong SAR)

**Comment by XPMilkChan** [comment]
> I tried to use LegacyUpdate on Chinese Traditional localised Windows XP (not MUI) and it finds no updates on this newly installed plain XP SP3. Is this normal?

There hasn't been any problem yet.
![bandicam 2022-12-03 15-24-45-555](https://user-images.githubusercontent.com/106049626/205431824-10e3b06c-566a-4a64-9547-945001115cc5.jpg)

**Comment by roytam1** [comment]
![image](https://user-images.githubusercontent.com/1192577/205437317-151544a7-f1c0-4fb7-a282-695d2d0aa694.png)
a plain XP SP3 CHT got this now, but "Details" tab is empty (can't expand?)

**Comment by XPMilkChan** [comment]
Yes, as the details will not show.
![bandicam 2022-12-03 19-38-39-860](https://user-images.githubusercontent.com/106049626/205441350-c716ff84-a8f4-404a-8764-ac766ce41991.jpg)

**Comment by XPMilkChan** [comment]
@kirb In the next version will you fix it?

**Comment by XPMilkChan** [comment]
Hmm bug?????????
![bandicam 2022-12-03 19-45-57-489](https://user-images.githubusercontent.com/106049626/205441574-9d206ecf-5656-4727-a9eb-1d88d9be09dc.jpg)

**Comment by kirb** [comment]
Thanks, fixed the sidebar links.

I’ll do my best to see what’s going on, I’ll need to install a non-English non-MUI copy of XP when I’m back home in a few days.

**Comment by kirb** [comment]
Sorry, I misread. @XPMilkChan and @roytam1, the Details popup doesn’t work for some reason, even in US English. I’ll just hide it for now.

**Comment by kirb** [comment]
I worked out the issue with the details list, fixed now.

![XP RTM-2022-12-04-22-19-32](https://user-images.githubusercontent.com/773309/205490717-ed6c5f0d-cc86-44ff-a901-1983fcab6337.png)

**Comment by XPMilkChan** [comment]
> I worked out the issue with the details list, fixed now.
> 
> ![XP RTM-2022-12-04-22-19-32](https://user-images.githubusercontent.com/773309/205490717-ed6c5f0d-cc86-44ff-a901-1983fcab6337.png)
Thank you very much for your quick fix.
