### ISSUE TITLE
LegacyUpdate fails to download files on Pentium CPUs

### ISSUE THREAD

**Issue by renodr** [kirb/LegacyUpdate#154]
Reported by a few people in Discord, it appears that LegacyUpdate's NSIS installer can't download files on Pentium CPUs. The exact reason appears to be related to illegal instructions in the modified NSXfer library that we use, but I'm not 100% certain on that just yet (though in https://github.com/kirb/nsis-nsxfer/blob/master/Makefile.mingw on line 42, we are setting -march to pentium2!) 

I just finished repairing my MMX 233 to take a look at this, so if changing the NSXfer library works I'll submit a PR to both the nsis-nsxfer repo for the Makefile fix, and a new DLL file to the setup folder in this repo.

**Comment by renodr** [comment]
![image](https://github.com/kirb/LegacyUpdate/assets/11901488/b647e188-4dba-4a84-acda-9aed18dafd4c)

Confirmed on my 233MHz Pentium MMX. Thankfully I don't need to do a complete reinstall everytime I need to test something on this system because I backed up the SD card, that was a good hour and a half worth of install time. :)

**Comment by renodr** [comment]
I recompiled NSxfer with a change to it's Makefile.mingw Makefile to change the CPU architecture to i486 from pentium2, and this seems to have done the trick! Still waiting on IE6 to install but it was able to download that and the prerequisite update just fine with this fix!

**Comment by kirb** [comment]
Fix released in Legacy Update 1.7.
