### ISSUE TITLE
Tells that all is up to date when there are updates missing.

### ISSUE THREAD

**Issue by Trancer03** [kirb/LegacyUpdate#158]
I'd upgraded .NET Framework to 4.6, then decided to downgrade to 4.5.2. I've uninstalled 4.6 and was expecting that Legacy Update will provide me with corresponding updates, but when I check for updates, it says that everything is up to date. Now I don't have any .NET Framework 4.x!
I've tried both: built in Windows Update and Legacy Update - all up to date!
I run Windows Vista Home Premium SP2 64-bit.

**Comment by PeterStrick** [comment]
Did you install .Net Framework Updates, while 4.6 was installed?

**Comment by PeterStrick** [comment]
Actually Windows Vista only ships with .Net 2.0 and 3.0. Upgrading from 4.5.2 to 4.6 replaces your 4.5.2 Installation.

You simply just need to reinstall 4.5.2

**Comment by Trancer03** [comment]
> Did you install .Net Framework Updates, while 4.6 was installed?

Yes.

**Comment by Trancer03** [comment]
> Actually Windows Vista only ships with .Net 2.0 and 3.0. Upgrading from 4.5.2 to 4.6 replaces your 4.5.2 Installation.
> 
> You simply just need to reinstall 4.5.2

I want the Legacy Update to provide me with 4.5.2 and both SQR updates, and it should if you don't have any 4.x, but it says that everything is up to date!

**Comment by se7enge** [comment]
I've also noticed that Legacy Update is not suggesting all available updates on my Windows XP Professional SP3 install. For example, 'Security Update for Windows XP SP3 (KB4024323)' is available in the download center and is not installed on my system, however, it is not being suggested as an available update.

**Comment by se7enge** [comment]
Legacy update also seems to report everything up to date even though there are more updates available for my system (Windows XP Professional SP3) in the download center. For example, 'Security Update for Windows XP SP3 (KB4500331)' is available in the download center but does not seem to get suggested as an update. I have installed with embedded support and have received other ESU/embedded updates, but many are missing.

Maybe I am misunderstanding how Legacy Update treats these available ESU updates for XP?

**Comment by Trancer03** [comment]
> Legacy update also seems to report everything up to date even though there are more updates available for my system (Windows XP Professional SP3) in the download center. For example, 'Security Update for Windows XP SP3 (KB4500331)' is available in the download center but does not seem to get suggested as an update. I installed Legacy Update with 'embedded' support enabled and have received other ESU/embedded updates, but many are missing.
> 
> Maybe I am misunderstanding how Legacy Update treats these available ESU updates for XP? Do some updates simply require manual installation?

As I understand that Legacy Update installs the minimum set of updates for the system to function properly. For example, when I still could get updates from Microsoft for my Vista during extended support, it was around the same ~212 updates that Legacy Update provides.
.NET Framework 4.5.2 with applicable updates for it was included in both!
