### ISSUE TITLE
Updates are installing successfully but still shows up when looking for updates after installing them

### ISSUE THREAD

**Issue by Shaknunic** [kirb/LegacyUpdate#16]
Probably this is a bug, I think it should be reported and that's what I'm doing...

- Atualização de segurança do Windows XP (KB2485663)
- Atualização de segurança do Windows XP (KB979687)
- Atualização de segurança do Windows XP (KB973904)
- Atualização de segurança para o Windows XP (KB923561)

**Comment by Typical0** [comment]
KB952069 for Windows 2000 also does the exact same thing.

**Comment by kirb** [comment]
Must be broken "is installed" logic for those updates on Microsoft's side. Basically Windows Update determines if an update is installed by looking at DLL versions and registry keys. If the server is sending the wrong logic, an installed update will show up in search results again.

I could possibly implement a fix on the server. I currently don't do any modification of the requests to/responses from the Microsoft server, but I might be able to do a find-and-replace if there's an easy fix.

For KB952069 I did find [this thread](https://answers.microsoft.com/en-us/windows/forum/all/windows-security-keeps-asking-me-to-update/55be4213-25de-4e86-b04e-e198f1ca7ecf) confirming the same behavior.

**Comment by atauenis** [comment]
Try purge C:\Windows\SoftwareDistribution and then reboot. This is working on modern systems, which also have this bug. Microsoft haven't fixed the problem even in latest OSes. I've seen this bug in 2000, XP ten years ago and in 8.1, 10 almost just now. Strange that have not seen in Win11, but may be this is just a luck. :)

**Comment by kirb** [comment]
Going to close as it’s not strictly a Legacy Update bug, but I’ll keep this in mind in case I ever see it happen myself so I can investigate.
