### ISSUE TITLE
Windows Vista SP2 is unable to update

### ISSUE THREAD

**Issue by NikNikovsky** [kirb/LegacyUpdate#163]
It's basically stuck when checking for updates in IE and the Control Panel.
There is some svchost activity when using IE (10-20% at the start, then basically nothing), and practically none when using the Control Panel

**Comment by NikNikovsky** [comment]
issue is resolved for now, updates are installing.

**Comment by thewanderingtraderm** [comment]
how did you fix it

**Comment by NikNikovsky** [comment]
Retrying I think
