### ISSUE TITLE
Doesn't work on Windows 11

### ISSUE THREAD

**Issue by ChaseKnowlden** [kirb/LegacyUpdate#165]
Opening Internet Explorer just opens Microsoft Edge, and LegacyUpdate doesn't work on modern browsers.

**Comment by drfsupercenter** [comment]
I mean, while you're right, I don't get why you'd want to.  The whole point of Legacy Update is to update *legacy* products, just use the regular Windows Update on 11?

**Comment by PeterStrick** [comment]
> Opening Internet Explorer just opens Microsoft Edge, and LegacyUpdate doesn't work on modern browsers.

Pretty sure you can use Internet Explorer Mode within Microsoft Edge

**Comment by ChaseKnowlden** [comment]
Ok, @PeterStrick.
