### ISSUE TITLE
Version Identifier falsely identifies LTSB/LTSC 2016+

### ISSUE THREAD

**Issue by legofanlovessayori** [kirb/LegacyUpdate#174]
Noticed the odd fact that installing Legacy Update on anything newer than LTSB/LTSC 2016 the website will identifiy the os as shown in the screenshot. 

![image](https://github.com/kirb/LegacyUpdate/assets/94994630/1483f6d7-1f32-4c3e-a632-eec2273d8a88)

For LTSB 2016 it would be "Windows 10 Enterprise LTSB 2015 1607" and for LTSC 2019 it would show "Windows 10 Enterprise LTSB 2015 1809"

**Comment by kirb** [comment]
Thanks for catching that, just changed it to say “LTSC” rather than “2015 LTSB”.
