### ISSUE TITLE
Legacy Update shows "Class Not Registered" error after installation of program

### ISSUE THREAD

**Issue by zekroman** [kirb/LegacyUpdate#175]
Hello, i wanted to try out Legacy Update on my Windows 8.1 N laptop that i refurbished myself, given that Windows Update is no longer pushing updates to the system, but every time i tried to install Legacy Update with all the boxes ticked, it would just give me a "Class Not Registered" error box and then it would crash, i wonder if the fact i'm using an N edition of Windows 8.1 is the reason for why it fails to launch (even going in Control Panel to run it, gives me the same crash error message).

I would appreciate some help, i even tried using the common fixes to fix the Class Not Registered error, and even i'm doing the DISM fix as of me typing this to see if it's some corrupt file, so any help would be appreciated.

I can provide my Laptop specs if need be, if it helps.

**Comment by kirb** [comment]
Hm I thought N editions only exclude media features, they should still include IE, right?

Could you try uninstalling through the Programs and Features control panel, then reinstall? If that doesn’t work and you don’t mind following a few steps, could you also try [this tool](https://www.seedy.gq/programs/lnst/) with Legacy Update 1.6.2, just to see if it was a new bug introduced in 1.7?

**Comment by zekroman** [comment]
Oh, i wasn't aware that Legacy Update would use IE as a proxy, i had the browser disabled on the Programs and Features part of the Control Panel, but once i re-enabled it and rebooted, Legacy Update started working. Thank you for helping me get this issue resolved, as i thought it would just be a native window within the operating system, not a proxy using IE.

And yes, N editions still include IE, but as i stated, i had disabled IE shortly after the setup.

**Comment by kirb** [comment]
Ah! No worries, I could probably add a check to see if IE has been uninstalled, and display a more useful error message. Thanks for bringing it up!
