### ISSUE TITLE
Legacy Update saying that I have to be logged in as admin even though I am

### ISSUE THREAD

**Issue by xX420MCplayerXx** [kirb/LegacyUpdate#181]
Hello. I use Legacy Update on my Windows XP computer, however, I tried running it today and it won't let me saying that I have to be logged on as an administrator. I tried it on the actual Administator account and it still said the same thing. It worked fine yesterday, so I don't know whats happening. I even tried rebooting, but it still didn't work.
![untitled](https://github.com/kirb/LegacyUpdate/assets/102683266/48086cc1-a076-42b8-a2a8-01f21f887c74)

**Comment by bonkmaykrQ** [comment]
I'm getting this exact same issue and so are at least 2 other people on Discord, I think it's server-side?

**Comment by kirb** [comment]
Sorry, yes this is a server issue. My fault. Working on it now.

**Comment by kirb** [comment]
Fixed now. Thanks heaps for posting/commenting here and on the Discord. (If it still doesn’t work, try again in about 15 mins.)

**Comment by xX420MCplayerXx** [comment]
thanks!
