### ISSUE TITLE
Your not logged in as an Administrator

### ISSUE THREAD

**Issue by vertaa** [kirb/LegacyUpdate#182]
I am receiving the mesage "Your not logged in as an Administrator". 

xpx86rtmsp3 no addons.

![image](https://github.com/kirb/LegacyUpdate/assets/67488797/5ad556da-9018-4e7a-adfa-56024a87810b)

**Comment by vertaa** [comment]
Ran ccleaner and it downloading and showing updates again.

**Comment by kirb** [comment]
Sorry for the issue, I think you must have still had the broken code from #181 in your cache. CCleaner would have cleared that.
