### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by ChaseKnowlden** [kirb/LegacyUpdate#190]
Windows 10 Internet Explorer no longer opens on Build 19045.3570, which is required for Legacy Update.

**Comment by sal-ammoniac** [comment]
try to use internet explorer mode

**Comment by kirb** [comment]
Does nothing happen when you open Legacy Update from the start menu, or is there an error message? If so could you paste a screenshot here?

**Comment by ChaseKnowlden** [comment]
LGTM, Still opens IE through installer on Windows 10.
