### ISSUE TITLE
Microsoft Edge opens when you open Internet Explorer on 2023-10 Windows 10 update

### ISSUE THREAD

**Issue by ChaseKnowlden** [kirb/LegacyUpdate#197]
LegacyUpdate fails to function on latest Windows 10 update.

**Comment by kirb** [comment]
Is this when you use the Legacy Update shortcut in the Start menu? Launching IE directly will do that, but launching through the Legacy Update shortcut should work.

**Comment by kirb** [comment]
Haven’t heard any response back and I can’t reproduce any issues, so closing.
