### ISSUE TITLE
Not working on any versions of Windows 7 while installing SP1

### ISSUE THREAD

**Issue by HamNCheeseBorger** [kirb/LegacyUpdate#198]
I have official installations of Windows 7 Pro, Home, and more (x86 and x64), yet legacy update will not work on any of them. 

It runs the updater and is installing SP1 but while the computer is doing that I get an error saying "Legacy Update has stopped working" after that the OS is unusable as legacy update makes registry changes during the upgrade of the service packs.

Not sure what to do here felt you all should know this is an issue.

**Comment by kirb** [comment]
This will be the same issue as #186, sorry for the problem. As a workaround you can log out of the LegacyUpdateTemp user it creates, log into your own user, and run Legacy Update setup again, unticking Enable Microsoft Update. It'll clean up the temp user when it finishes (or if you just click Cancel).

Will close this as a duplicate, but thanks for posting regardless.
