### ISSUE TITLE
Test on Win2k

### ISSUE THREAD

**Issue by kirb** [kirb/LegacyUpdate#2]
Haven't tested the ActiveX control on 2k yet. Best case it works on RTM but that might be asking too much, I'd be fine with it working on SP4 + IE6.

**Comment by kirb** [comment]
Works for me after installing KB835732 (which updates kernel32.dll with functions VC++08 needs). Seems there's some issue with using the site on non-US English installs of 2k. Doesn't seem to be an issue on XP. Reproduced by 2 people who hit the same "LegacyUpdate not installed" error page.

**Comment by rfinnie** [comment]
I'm not able to get win2k SP4 working.  Ran the installer on a clean VM, it installed IE6 and the rest of the components, but http://legacyupdate.net/windowsupdate/v6/ has a (I'm assuming ActiveX) error, with the main pane just showing "Loading...".
![image](https://user-images.githubusercontent.com/704589/200185243-bf23782d-59b1-4a50-a6fe-3ceb5f9fc13c.png)

**Comment by kirb** [comment]
@rfinnie I’m not sure what’s going on there. Just tested SP4 + IE6 and it’s working fine. Could you try Ctrl-F5?

**Comment by rfinnie** [comment]
> @rfinnie I’m not sure what’s going on there. Just tested SP4 + IE6 and it’s working fine. Could you try Ctrl-F5?

Interesting, it works after Ctrl-F5... each time.  As in, I just booted up the VM again, loaded IE and it gave the error, did a Ctrl-F5 and was able to do the first round of updates.  Then I rebooted, loaded IE again, same error, works after Ctrl-F5. Sounds like there's some pervasive caching going on somewhere.  Anyway, thanks!

**Comment by kirb** [comment]
That’s a weird one, but glad it was an easy fix. 

Will close this now because I think Win2k is figured out, the 1.1 installer seems to have resolved the issues people were having with en-gb installs of 2k.
