### ISSUE TITLE
IE6 on Windows 2000 is installing English only

### ISSUE THREAD

**Issue by atauenis** [kirb/LegacyUpdate#23]
Installing Legacy Update on localized builds of Windows 2000 without IE 6 SP1 always updates IE to English version. Installing an MUI does not solves the problem, as MUI support is available only when Windows 2000 language is English. So user gets a mix of localized and English interface. Windows Explorer also became English.

However, the Legacy Update still working correctly, except some glitch on layout.

![2022-11-28_12-51-02](https://user-images.githubusercontent.com/4800266/204252700-67634cb8-5155-458c-9f4a-656f623893d5.png)
![2022-11-28_13-17-21](https://user-images.githubusercontent.com/4800266/204252826-e3391c0b-186f-408a-8a25-a3c93e9b9d7f.png)

Looked into source, seems that `activex/build/Download2KXP.nsh` have hardcoded path to MSIE 6 installer.

Online installers of IE6 are preserved in Web Archive, and they can be installed by some kind of overriding `http://www.microsoft.com/windows/ie/ie6sp1/download/rtw/x86/ie6sites.dat` file. I've [successfully do this](https://github.com/atauenis/webone/discussions/72) via own proxy, but without it the only way is HOSTS file spoofing and some fake server, which will return patched file.

I hope, full installers are also saved in some archives, but I is unable to find their URLs.

The good news is that after reinstalling localized (Russian in my case) IE6 SP1, all 15 its updates successfully found and re-installed again. But the interface glitch is still here.

---

Some googling found, that Windows Update v4 was distributed MUIs for IE 5/5.5/6 too:
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KAR_25FF0E79CAECA33461F0476E9B2ECB9DD1D0DE37.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KBR_DFC2E0488A125CDFDA4E87516D2012821B8EC883.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KCN_BD30911DB41ABFD255F7DCFF598CF3D959448B15.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kcs_929122A24FE68A4D2EEA252A2FA6F90FF5B87BAF.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KDE_88D6105BFF12C948CB6EE3D74A6723188F61B1E7.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kel_268DB1F705AE38E665B0B5AC346E5000D986AF32.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2ken_46D9DB4A219386B17AFEF8B45BE8036B9140895C.exe
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kes_6A0553D4A52CF2543461A408F4D3C4A2900A854C.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kfi_F5A284E574ECAAB7265AA14934C4072D6E80ACE2.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kfr_B90349373ED24D6491CE1A59F6995268F4F6CC20.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KHE_2BC573C110C828DD27808F1A674C35E647C353D3.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Khu_C61EB62139E3BA08D7A13BBD486A72CC91F6B9C1.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kit_34AD6D2B9C87952238EDABDFE5D1870D1BED11FF.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KKO_AB57C24FE1071B47F476244B3876A96ED1D326ED.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Knl_42CF8D0A2612E59B16035103BE28B7D278CAFBD8.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kno_54371B3324962FA62ECDCACB0461AF3213E5277B.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kpl_ABAB09CC9D27C2DCDE19F38FC642DBE3432374D2.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Kpt_12F6E901E2F15D520157224EA84EA79F38609754.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KRU_177C3CF17C343A932CACD5368485ECA9A18C61B5.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2Ksv_FDC2564E9632FB51B9D733709BC141FEB1500E55.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KTR_F909C38EF4B4275AC6570FCA8E46810E5178DEEB.EXE
* http://download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ieui2KTW_BB46F0033615E91F2C7919419788502F0D5E41D8.EXE
* Some 5.01/5.5/6.0 RTM MUI links: http://forum.ru-board.com/topic.cgi?forum=5&topic=0115&start=320#9

What about to add them to Legacy Update?

**Comment by kirb** [comment]
Thanks heaps for being so detailed! Really appreciate it.

Sidebar section headings is probably my fault from a CSS change I made a week or two ago, now you mention it I don't think I tested it in IE6... I'll fix that, thanks. The icons being in weird locations seems to be a bug with the JS library I use to work around the IE6 PNG transparency issues, haven't figured that one out just yet.

I did try mirroring the IE installer files on my server, which should have allowed non-English/non-Win2k installs to work, but the flag documented in [KB200007](http://web.archive.org/web/20120829125145/http://support.microsoft.com/kb/200007) just doesn't seem to work for some reason. Feel free to play around with getting the installer to download from http://content.legacyupdate.net/legacyupdate/ie/ie6sp1/x86/ie6sites.dat if you'd like. It seems what I have (which is a mirror of what Wayback Machine has) should be everything for English and Russian. (Other languages are mostly incomplete.) I was trying with `iewz6d.exe /L:"http://content.legacyupdate.net/legacyupdate/ie/ie6sp1/x86/ie6sites.dat"`, which is correct according to the KB, yet it insisted on connecting to the official microsoft.com url anyway. I wrote a Fiddler rule to replace the response with a local copy of ie6sites.dat, which worked, but again it never loaded ie6sites.dat from the site itself.

Unfortunately it seems there never was a "full" installer, they just expected you to run the web installer with specific flags to make a full download of the cabs (e.g. see [here](https://petri.com/download_the_full_ie_package/)). Seems to be the case for all of IE 4 - 6.

So do you suggest it should be fine installing IE6 as it does now, and then installing the matching MUI update over the top? Or should I make language-specific SFXes? (Will be a challenge to cover every language, will need to scour the internet for the cabs not archived by Wayback Machine)

**Comment by atauenis** [comment]
According to [KB264550](https://web.archive.org/web/20060320221042/http://support.microsoft.com/default.aspx?scid=kb;en-us;264550), IE MUIs are working only with an "MultiLanguage version of Windows 2000" (probably meaning English version with an MUI pack installed over it). So on non-English systems MUI packs are useless.

Tried to install Russian IE MUI over English IE on Russian Win2k and over English IE on English Win2k with MUI. In first case I'm got [almost nothing](https://user-images.githubusercontent.com/4800266/204281129-eeb1aca5-cc1e-4a93-95ae-15d7a8236e68.png), in second a perfectly localized everything. So said in KB264550 is confirming.

> Unfortunately it seems there never was a "full" installer

Yeah, all offline IE installers I've known are set of ~80 files, zipped or sfx-zipped together. Sometimes with a `This folder is safe to delete.txt` file. And not a single Microsoft-signed EXE.

> So do you suggest 

I think it will be better to make IE6 SP1 installation optional with an warning message if user unchecks IE option.

Also I've remember that in ~2008 the Windows Update v4 worked in IE 5.0, 5.5 too. WUv6 on Win2k also fully worked via IE 5.5 without problems (finds updates, installs them), and at least successfully displayed an error in IE 5.01. :) So probably it will be possible to made some support for IE 5.x (if Update Agent can work without IE6).

**Comment by kirb** [comment]
Thanks for testing, so separate IE installers for each language is definitely necessary then. Hopefully better archives of the non-English cabs are out there somewhere, because the Wayback archives are very incomplete. 

The site definitely works on IE5.5, though I figured it's just less work for me on the site maintenance, and more likely what the user wants anyway, to update to IE6.

**Comment by stdin82** [comment]
WU links still works for IE6 SP1
http://www.techtalk.cc/viewtopic.php?p=19526#p19526
taken from iebatch.txt included with ie6setup.exe

<spoiler><summary>IE6 SP1</summary>


```
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-ara_b1720a72becd05142cb4ccbb23205c76b51d29e2.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-chs_6d93ab8525d3b6f775faf692caaa4c8267c8a22b.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-cht_1899bffb8ebf36c0a58686f04cc1d721c419792d.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-csy_2789a030bba2128fc90e0475e2530c300ed5defc.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-dan_0c178b2634a97a4879c172797b21a59e567d18e6.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-deu_2a13ac14e403ad4a1c6877fe478067e81ac20da8.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-ell_15a4e43c8922f658eddd5d57d23c11e0fa55dce9.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-enu_91192253c8d3cf7beff22e68ae1fdff9638bf546.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-esn_a9c53ad93bae78becf2b06f6d317ef7ef66a2abe.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-fin_1a369fcc86e803128144e17246e16d0a27a8c35b.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-fra_0bc4219b3119a127503cd93863cfedfb1e37bd55.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-heb_70518dd1d09d702975b8e44a22c88e139f168975.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-hun_1eeed3e7b3e6bd311c17c0d97f67ec12df8b4b85.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-ita_2c6ab20b41114e53646ebb56ff6d269fd86fba36.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-jpn_b1e1e8b9dbbf440d8964ec375348674502ef0728.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-kor_f61474b056ae37c5e9670978c6d3b24f4800d7f5.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-nld_3fd676fe34f93471f4db9a0a1f3ef5c3ed8e5f43.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-nor_72a81d06462c5a66f9531f4f226b13463698dd24.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-plk_14889750985a9d29490886c2e901ef3bc69c4ff5.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-ptb_448df44aea5d853e4954d48411b1953569df23c2.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-ptg_5892593c72f702ba6c7d88b47c2bd7c5707081fd.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-rus_842c289d0887bbe2e4edea1ff3763addc8d77db5.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-sve_db8dcfef073f2df327fc3706d9a141b6124cfed0.cab
http://www.download.windowsupdate.com/msdownload/update/v3-19990518/cabpool/ie6sp1-wucab-trk_64479241feb2f783f851b16791d5d1c684d94a66.cab
```
</details>

`/L:""ie6sites.dat""` indeed not working, but using `/B:""iebatch.txt""` work

IE5 (all versions) WU links also still working
e.g.
```
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie55sp2/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie55sp1/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie55rtw/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie501sp2/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie501sp1/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie501/x86/en/ie5setup.exe
http://www.download.windowsupdate.com/msdownload/update/v3/static/ie50b/x86/en/ie5setup.exe
```

**Comment by kirb** [comment]
@stdin82 Where did you find the list of wucabs? I can't seem to find where they came from, WU catalog only lists the ENU build (https://www.catalog.update.microsoft.com/Search.aspx?q=KB326489). I'm surprised you found them!

I don't suspect there's a separate cab for NEC98-JPN given the urls don't include "x86" ("NEC98" takes the place of "x86" in Win2k patch filenames for the NEC PC-98 variant), would you know?
