### ISSUE TITLE
LegacyUpdate-1.4.1.exe crashes on launch

### ISSUE THREAD

**Issue by robastala** [kirb/LegacyUpdate#37]
I am using Windows XP Home SP3 french. I was getting error 82 with version 1.4, but this version won't start. See screenshot below.

If you need more info just ask.

Thanks

![LegacyUpdate-1 4 1 error](https://user-images.githubusercontent.com/92332373/206277609-821374d3-4be5-4cd0-9c19-88240c0f1fdd.jpg)

**Comment by terrul** [comment]
I'm having the same issue.

**Comment by kirb** [comment]
Seems to be happening inconsistently, works for some but not for others. I cleared the Cloudflare cache for the file, give it another try and let me know how it goes.

**Comment by terrul** [comment]
> Seems to be happening inconsistently, works for some but not for others. I cleared the Cloudflare cache for the file, give it another try and let me know how it goes.

I think I figured it out. I already had the unofficial sp4 installed. Latest version didn't like that.

**Comment by robastala** [comment]
> Will keep looking into it. @robastala were you running SP3 or unofficial SP4?

Clean install & added the drivers. Windows XP home SP3 French but... nLite version. Can't remember the source exactly. From what I remember was from an official SP2 disk and did nLite version to add SP3. Created back in 2009.... so long time ago...

**Comment by robastala** [comment]
> Will keep looking into it. @robastala were you running SP3 or unofficial SP4?

Clean install & added the drivers. Windows XP home SP3 French but... nLite version. Can't remember the source exactly. From what I remember was from an official SP2 disk and did nLite version to add SP3. Created back in 2009.... so long time ago...

**Comment by BurnedPinguin** [comment]
I'm having the same problem too except that when I move the file to C:\ root as [robastala](https://github.com/robastala) did, I get farther like they did when they moved it to their download folder but it still crashes mid-install. Launching from cmd or explorer makes no difference. Launching from anywhere but not the C:\ drive crashes before the installer can even pop up.

**Comment by mina354** [comment]
^ I have the same problem.

**Comment by Njmcq** [comment]
So I have the same issue and tried to find a workaround. After attempting to open it from both the Desktop and C: directory, I placed the .exe on the Desktop and opened up the Command Prompt. I dragged the .exe into CMD and pressed Enter. The GUI shows but resulted in the same error. However, as soon as I then double-clicked on the Desktop icon and tried it, it worked fine.

I did however get the following error message at the end of the installation:
![untitled](https://user-images.githubusercontent.com/83850979/206830713-d2fae864-7385-4742-9a32-66080a881df1.JPG)
But dismissing it and proceeding to check for updates goes without a hitch. Such a peculiar issue!

**Comment by Njmcq** [comment]
Hi @RayyanHodges,

That is quite odd, because doing the same thing didn’t work for me. It got me further than just running it from the Desktop, but it still crashed.  Tried it multiple times to make sure.

Glad to hear that yours worked though!

**Comment by RayyanHodges** [comment]
> Hi @RayyanHodges,
> 
> That is quite odd, because doing the same thing didn’t work for me. It got me further than just running it from the Desktop, but it still crashed. Tried it multiple times to make sure.
> 
> Glad to hear that yours worked though!

Very interesting, what platform and version of Windows are you using? Genuinely curious...

**Comment by Njmcq** [comment]
> > Hi @RayyanHodges,
> > That is quite odd, because doing the same thing didn’t work for me. It got me further than just running it from the Desktop, but it still crashed. Tried it multiple times to make sure.
> > Glad to hear that yours worked though!
> 
> Very interesting, what platform and version of Windows are you using? Genuinely curious...

Running XP Home Edition SP3 on a Dell Inspiron 600m. Not sure of the specific build, though. But I did a few clean installs since the Update MiniTool bloated my C: drive, among other issues. So unless I have a dodgy ISO on my CD (doesn’t seem that way), I have no idea why our experiences could be different?

**Comment by RayyanHodges** [comment]
> > > Hi @RayyanHodges,
> > > That is quite odd, because doing the same thing didn’t work for me. It got me further than just running it from the Desktop, but it still crashed. Tried it multiple times to make sure.
> > > Glad to hear that yours worked though!
> > 
> > 
> > Very interesting, what platform and version of Windows are you using? Genuinely curious...
> 
> Running XP Home Edition SP3 on a Dell Inspiron 600m. Not sure of the specific build, though. But I did a few clean installs since the Update MiniTool bloated my C: drive, among other issues. So unless I have a dodgy ISO on my CD (doesn’t seem that way), I have no idea why our experiences could be different?

Ah, probably explains the issue, I was told by @kirb that you should only run the setup file from C: if you are on Pro, not home.


![image](https://user-images.githubusercontent.com/11124303/207286577-b4024c22-b48b-4333-a95e-4ee8d2c7233f.png)

Maybe that might be your issue? I am using Windows XP Pro SP3 in a VMWare Virtual Machine.

**Comment by themacintoshnerd** [comment]
I know I'm late to this but downloading it on modern computer and moving it to my XP SP4 install worked fine. Downloading in IE didn't.

**Comment by vertaa** [comment]
Is there a way for legacyUpdate to load IE?

When I click on the shortcut from the startmenu, it loads my third party browser and I receive an error.

![image](https://user-images.githubusercontent.com/67488797/209484022-cab4690d-6f54-4ec1-b1b7-acf2f96b43fc.png)

Is there a fix for this?

**Comment by kirb** [comment]
@vertaa I’m not sure what that browser would be, but that sounds like this browser is overwriting IE’s COM object registrations in the registry with its own implementations. I can’t guarantee anything will work as expected because of that. I wrote the code used by the shortcut specifically to use the IE COM interface to ensure it would always launch IE, and not use any other browser. Your browser is breaking that API contract, unfortunately.

**Comment by vertaa** [comment]
Hello kirb,

I am using 360ChromePortable_13.5.2022_rebuild_3_ungoogled_MSFN.zip. Is there a way to default LegacyUpdate to load IE instead of the third party browser.
