### ISSUE TITLE
Various issues with the automatic reboot

### ISSUE THREAD

**Issue by makuhlmann** [kirb/LegacyUpdate#39]
OS: Windows 2000 (SP4, IE6 preinstalled)
Language: German

Issue 1: 
When the system reboots after the installation of KB835732, it logs into the LegacyUpdateTemp account, after which it displays the message “Log on as an administrator to install Legacy Update”. Confirming this message with OK just logs the user in to the temporary account. The account has standard user permissions (“Benutzer”-group on a German system, maybe different languages cause this issue).

I gave the account admin permission and rebooted, after which the process continued. However, the user folder is still present and has not been deleted.

Issue 2:
When using a modem connection or a connection that requires starting it up after boot, the installer will fail to download further updates and thus fail to continue. This could be avoided by downloading all required updates during the first step and saving them in a temporary location that can be accessed by all accounts.

On a personal note, I would appreciate to see more configurability in the installer. I don't like that a temporary account is being created without being informed or asked about it in the installer. Both the reboot and the automatic reboot using a temporary account should be an option that I can untick. Also I'd like to be able to unselect options that are currently set to be mandatory, like Windows Update Agent. Of course it doesn't make much sense for productive use, however it makes troubleshooting various issues way easier. Perhaps there could be an “Express” mode that uses the current logic and an “Advanced” mode that allows the user to configure every aspect of the installation.

**Comment by makuhlmann** [comment]
> Would you mind opening C:\Windows\inf\defltwk.inf and doing a find for “SceInfAdmins”? On English installs, you would see SceInfAdmins = "Administrators" - on your German install, do you see the German translation for “Administrators” instead?

Yep, on that system the group is called "Administratoren". All groups in the strings-section have their name localized.

> Do you still see the folder after doing another reboot, and if so is there anything left in it?

You are right, now it's gone after another reboot.

**Comment by kirb** [comment]
Implemented grabbing the localised string for Administrators in 1.6.2 (although by using the proper API for getting the group name, because I realised defltwk.inf doesn't exist in XP Home).

**Comment by kirb** [comment]
The second issue is now addressed by [Legacy Update 1.7](https://github.com/kirb/LegacyUpdate/discussions/169), so going to close this now.
