### ISSUE TITLE
LegacyUpdate immediately crashes when running the setup file

### ISSUE THREAD

**Issue by RayyanHodges** [kirb/LegacyUpdate#40]
Hello!

Just opening this GitHub issue as I have been trying run the LegacyUpdate installer on an emulated copy of Windows XP with real hardware via PCEm where when I run the executable from your site, it instantly crashes. I have attached a screenshot of what I mean:

![image](https://user-images.githubusercontent.com/11124303/207248364-7752ccd6-363c-49b5-96bb-6e207828cd4a.png)

This is the hardware I have virtualized FYI.

![image](https://user-images.githubusercontent.com/11124303/207248585-0cd4ff72-0cd4-4f62-9980-71a5bb05e234.png)

Thank you in advance!

**Comment by kirb** [comment]
Really sorry about the crash. It’s covered by #37 so I’ll close this as a duplicate. Would recommend using version 1.4 as a workaround (only on XP Pro, don’t do this on Home), or alternatively we discovered that it’ll run if you move it to the root of C:.

**Comment by RayyanHodges** [comment]
Have confirmed saving the setup file to the root of the C: drive has solved the issue.

Thanks again!
