### ISSUE TITLE
Windows Update Agent failed to install. Error code: 82

### ISSUE THREAD

**Issue by AlpacaGamerNoo** [kirb/LegacyUpdate#43]
I got this error while trying to install Legacy Update and I don't know what to do, any help?

**Comment by AlpacaGamerNoo** [comment]
oh really? thx

**Comment by AlpacaGamerNoo** [comment]
> Which version are you trying to install? The Dev fixed that error in v1.4.1 (Latest).

I am using the latest version

**Comment by kirb** [comment]
Can you try again with Legacy Update 1.5?

**Comment by kirb** [comment]
If there are still issues with this I think they should be fixed with Legacy Update 1.6. If not, feel free to reopen this issue or create a new one.
