### ISSUE TITLE
9x and helping

### ISSUE THREAD

**Issue by stubbertville** [kirb/LegacyUpdate#44]
would I be able to help to get 9x supported?

**Comment by E-System33** [comment]
![image](https://user-images.githubusercontent.com/89921808/215321620-d4e25fac-2d48-4f10-b046-f5ddf7286990.png)

**Comment by sJARB** [comment]
It's a good idea, I thought the same thing when I discover the site !
Also, NT4 has WU support, it'll be the last if 9x is supported

**Comment by kirb** [comment]
Not sure why I missed this thread. Hopefully you've seen [Windows Update Restored](http://windowsupdaterestored.com/), they've done some pretty great work and I'm excited for what they've done.

Legacy Update still has some plans to do something here ([more info](https://legacyupdate.net/faq/win9x)), if you want to discuss (or just observe), you can [join Discord](https://legacyupdate.net/discord). Thanks heaps for your interest!
