### ISSUE TITLE
Main web site, subdomain 'www' should redirect to main site

### ISSUE THREAD

**Issue by wickens** [kirb/LegacyUpdate#49]
Minor issue, and perhaps because I was in full legacy mode, I entered `www.legacyupdate.net` into IE5 on Win 2K and because it didn't resolve, ended up with a failed MSN search. 

Suggestion would be for `http://www.legacyupdate.net` to 301 redirect to `http://legacyupdate.net`

**Comment by kirb** [comment]
I hate `www.`, but I did reluctantly eventually fix the www subdomain to redirect to non-www a while back.
