### ISSUE TITLE
Windows update on Windows XP SP3 (x86) fails to update

### ISSUE THREAD

**Issue by CCF100** [kirb/LegacyUpdate#5]
All I get is the following error code:
![image](https://user-images.githubusercontent.com/29297989/197378764-19316738-8d94-40cb-b775-65c75a9acf0b.png)

**Comment by kirb** [comment]
That error code corresponds to "automation server couldn't create object". That could mean either LegacyUpdate.dll somehow isn't registered, or perhaps the update agent is outdated.

Do you see the version info at the top of the homepage? If so, is the update agent version outdated or supported?

If you don't get that, try running in a command prompt:

```batch
regsvr32 "%ProgramFiles%\Legacy Update\LegacyUpdate.dll"
```

You should get "DllRegisterServer in ... succeeded." Restart IE and see if that works.

**Comment by CCF100** [comment]
> That error code corresponds to "automation server couldn't create object". That could mean either LegacyUpdate.dll somehow isn't registered, or perhaps the update agent is outdated.
> 
> Do you see the version info at the top of the homepage? If so, is the update agent version outdated or supported?
> 
> If you don't get that, try running in a command prompt:
> 
> ```batchfile
> regsvr32 "%ProgramFiles%\Legacy Update\LegacyUpdate.dll"
> ```
> 
> You should get "DllRegisterServer in ... succeeded." Restart IE and see if that works.

I just installed Legacy Update, and ran your command...
It didn't change the output when I attempt to update again. I also do not see the update agent version on the page.

**Comment by RickzDO** [comment]
working here! Xp SP3 Pro + all post ready updates, installed and checked for updates, fome updates for net framework 4 and office 2010...

**Comment by kirb** [comment]
Yeah, I'm not too sure what's going on here... sorry @CCF100.

What is the version of C:\\Windows\\System32\\wuapi.dll? (right click &rarr; Properties &rarr; Version &rarr; File Version). On XP SP3 it should be 7.6.7600.256.

I'd also say try

```batch
regsvr32 "%windir%\System32\wuapi.dll"
```

although I'm still not too confident in what the issue really is, just taking a shot in the dark currently.
