### ISSUE TITLE
Version 1.4.1 Not Updating Update Agent on Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by Mrgibs** [kirb/LegacyUpdate#51]
When running the installer on Windows Server 2008 R2, the option to update the update agent is not given.

The only options are to update the root certificates store, and Legacy Update itself.

![image](https://user-images.githubusercontent.com/5975038/208252861-1eba65b8-6bb8-471d-b13b-d6e1211fc542.png)

**Comment by kiriiniko** [comment]
found a fix for this, you can manually update the agent here:
https://learn.microsoft.com/en-us/troubleshoot/windows-client/deployment/update-windows-update-agent

**Comment by Mrgibs** [comment]
Installed the version from Microsoft's site. Seems like its still not good enough.

![image](https://user-images.githubusercontent.com/5975038/208314522-33fc039c-54e3-4e88-9709-76d790105a26.png)

**Comment by kirb** [comment]
7.6.7600.320 should be sufficient, although the site will check that you have the *absolute* latest possible for your Windows version, in this case 7.6.7601.19161. (That Microsoft docs page is misleading, the versions they link there are the final ones they released in the form of an .exe installer. All subsequent versions are .msu patches delivered through Windows Update.)

I’ll fix the installer checks though, the Windows version querying library I use differentiates between “client” and “server” variants of Windows, which has been frustrating to work with. So where I’ve done checks for “is Windows 7”, it literally means *only* “is Windows 7”, not “is Windows 7 or Server 2008 R2” like I was hoping. Easy problem to fix though.

Never tried this, but is it possible that if you right click the exe &rarr; Properties &rarr; Compatibility, there’s an option to run it in compatibility mode for Windows 7 SP1? If so, that will work, and is safe to do (Windows 7 and Server 2008 R2 share all their updates in common).

**Comment by RaduTek** [comment]
I've run into the same issue. Have tried uninstalling and setting the compatibility mode to Windows 7 for the installer but that changed nothing. 

Also on my install of Server 2008 R2 SP1 there isn't an option for Windows 7 SP1 in the compatibility mode list.

**Comment by Annunaki** [comment]
Same problem here on a fresh 2008 r2 standard sp1 installation on real hardware (Dell Power Edge T310), downloaded the manual Update Agent package from Microsoft then re-launched legacy update, The checking progress bar hangs 1/4 of the way but if left it will eventually show a page with available updates.

**Comment by kirb** [comment]
Fixed in 1.5.
