### ISSUE TITLE
explorer. exe has generated errors and will be closed by Windows.

### ISSUE THREAD

**Issue by wickens** [kirb/LegacyUpdate#52]
Tried to update Windows 2000 Professional. 

It successfully rebooted, logged in as the temp user account and installed, but when it rebooted after that (and I log in as my usual user) I get the following error: `explorer. exe has generated errors and will be closed by Windows.`.

I get the same error when I start task manager using CTRL + ALT + DEL, so I am unable to launch Event Viewer. 

Also occurs when starting in safe mode, although the build version indicated that SP 4 did install. 

**Screenshot (UTM on Mac).**

<img width="708" alt="Screenshot 2022-12-17 at 20 52 28 GMT" src="https://user-images.githubusercontent.com/72025547/208265631-fdd71d62-d043-4b35-8bb7-05d2bbbbe1c7.png">

Let me know if you need any more information or I can help in any way.

**Comment by kirb** [comment]
Sorry that this got lost in my inbox. This seems to be the only case I've seen of this, so unfortunately I think you just got unlucky for some reason. If you want to salvage the VM, you might be able to get into Safe Mode with Command Prompt and run the service pack uninstaller using:

```
C:\WINNT\$NtServicePackUninstall$\spuninst\spuninst.exe
```
