### ISSUE TITLE
"Windows Update Agent failed to install. Error code: 82"

### ISSUE THREAD

**Issue by HilbertIdeals5** [kirb/LegacyUpdate#53]
<img width="1440" alt="Screenshot 2022-12-17 at 1 58 02 PM" src="https://user-images.githubusercontent.com/63978875/208267896-51be967a-b6f4-473b-a887-591acecdfed1.png">

As per the title, a window showing this error code shows up a couple of seconds after starting the Legacy Update installation, but what does it mean? This result came up on both of the two Windows XP VMs I've made.

Specifically, I'm using version 1.4 (1.4.1 said "encountered an error" immediately upon running it; however, I'm installing this on XP Home Edition, not Professional). This is XP Home Edition SP3, so I had all the default boxes checked, meaning only "Enable Embedded 2009" was unchecked. I'm also running this in Virtualbox.

(Also, is this the appropriate place for support questions?)

**Comment by AlpacaGamerNoo** [comment]
same problem here (only the fact its running on actual hardware)

**Comment by BigGreenDinosaur** [comment]
I am having the same problem as well. I am running it on real hardware too.

**Comment by HilbertIdeals5** [comment]
A note is that I tried installing this on Windows Vista, and it worked just fine.

**Comment by stdin82** [comment]
See the fix in [1.4.1](https://github.com/kirb/LegacyUpdate/releases/v1.4.1.0)
download and install WUA [7.6.7600.243](http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.243/WindowsUpdateAgent30-x86.exe) manually

or if you want to use [7.6.7600.256](http://download.windowsupdate.com/windowsupdate/redist/standalone/7.6.7600.320/WindowsUpdateAgent-7.6-x86.exe), don't launch it directly
use 7-zip or WinRar to extract WUA-Downlevel.exe, then run if from comand prompt
`WUA-Downlevel.exe /quiet /norestart /wuforce`

**Comment by kirb** [comment]
Fixed in Legacy Update 1.5
