### ISSUE TITLE
Legacy Update fails to work on Windows XP Professional x64 Edition SP2

### ISSUE THREAD

**Issue by GriffintheFolf** [kirb/LegacyUpdate#6]
This appears to be a similar problem to issue #5, where the installed version of wuapi.dll is too old. It results in this error:
![image](https://user-images.githubusercontent.com/26304783/200144553-56354122-1280-44d2-bfce-758e747db7a5.png)

With a stock installation of Service Pack 2, the version of wuapi.dll is 5.7.3790.3959. It does not appear as though the Legacy Update installer includes an updated client to install, but I found this workaround:

1. Install Legacy Update as normal
2. Download the updated Windows Update 3.0 client from [this link](http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/WindowsUpdateAgent30-x64.exe). The installed version of wuapi.dll is 7.4.7600.226.
3. Install the update, try again, and profit

The site complains the update client version is outdated, but it seems to work anyway.
![image](https://user-images.githubusercontent.com/26304783/200144612-d13d57e4-7c6c-46e5-97e0-d250ce010c7e.png)
![image](https://user-images.githubusercontent.com/26304783/200144617-2ccdca12-856f-4287-a6d8-06fe368774bd.png)

I understand that XP x64 Edition is a bit of an edge case, but would it be possible to integrate this updated client into the installer?

**Comment by kirb** [comment]
Thanks heaps for investigating and reporting this! I just figured out why it’s broken… copypasta mistake [here](https://github.com/kirb/LegacyUpdate/blob/main/activex/build/Patches.ini#L101) 🤦‍♀️ It’s definitely supported, although I haven’t specifically been testing on XP x64.

**Comment by kirb** [comment]
Fixed in 1.2. Thanks again!
