### ISSUE TITLE
LegacyUpdate website crashes Internet Explorer 8 - Windows XP

### ISSUE THREAD

**Issue by RayyanHodges** [kirb/LegacyUpdate#67]
Hello!

After running various updates on a Windows XP virtual machine under PCem and having to reboot my machine to complete the updates. the LegacyUpdate website crashes the browser and will not load the homepage at all.

Here is a screenshot of the crash:
![image](https://user-images.githubusercontent.com/11124303/209418780-b138a652-5238-4f8a-97da-9b12fb2c552d.png)

Here are the specs I am emulating if that helps:
![image](https://user-images.githubusercontent.com/11124303/209418811-629dafee-50df-41bf-92c3-421159254bf2.png)

Thanks in advance!

**Comment by RayyanHodges** [comment]
Hiya,

I was able to view the website in IE8 in a Windows XP VMWare virtual machine, I am going to close this as I believe it is a performance issue with PCEm.

**Comment by RayyanHodges** [comment]
Hiya,

I was able to view the website in IE8 in a Windows XP VMWare virtual machine, I am going to close this as I believe it is a performance issue with PCEm.

**Comment by kirb** [comment]
I think it has to be, yeah. The crashing module is the Windows 2D graphics library (GDI+), and the site does depend on some DirectX and GDI+ drawing features (via VML) to ensure correct UI rendering. I can imagine possibly something is incorrect with how the GPU is being emulated.

**Comment by AstaFatherSatan** [comment]
This is happening after updating on my ThinkPad r30 only after updating with legacyupdate from clean sp3 installation. Any ideas?

**Comment by kirb** [comment]
Realising now that this is because of the issue of SSE2 updates being installed on a non-SSE2 capable machine (Microsoft released these updates without any checks for compatible CPU). Opened #89 to encapsulate the discussion of how we can fix this. For now I think the most reasonable solution is to not enable POSReady updates on machines with CPUs prior to Pentium 4 or Athlon 64.
