### ISSUE TITLE
install error.

### ISSUE THREAD

**Issue by vertaa** [kirb/LegacyUpdate#72]
I tried Windows XP Professional SP3 x86 - Integral Edition 2022.9.9. 

It installed without errors on a Lenovo T61P.

However when I try to install "LegacyUpdate-1.4.1.exe" I receive an error.

![image](https://user-images.githubusercontent.com/67488797/209461822-72008800-e0b1-43bd-801c-1626500ae9ca.png)

<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="LegacyUpdate-1.4.1.exe" FILTER="GRABMI_FILTER_PRIVACY">
<MATCHING_FILE NAME="LegacyUpdate-1.4.1.exe" SIZE="525194" CHECKSUM="0x2171E14E" BIN_FILE_VERSION="1.4.1.0" BIN_PRODUCT_VERSION="1.4.1.0" PRODUCT_VERSION="1.4.1.0" FILE_DESCRIPTION="Legacy Update" COMPANY_NAME="Hashbang Productions" PRODUCT_NAME="Legacy Update" FILE_VERSION="1.4.1.0" LEGAL_COPYRIGHT="© Hashbang Productions. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x60000" UPTO_BIN_FILE_VERSION="1.4.1.0" UPTO_BIN_PRODUCT_VERSION="1.4.1.0" LINK_DATE="09/25/2021 21:57:46" UPTO_LINK_DATE="09/25/2021 21:57:46" VER_LANGUAGE="English (United States) [0x409]" />
</EXE>
<EXE NAME="kernel32.dll" FILTER="GRABMI_FILTER_THISFILEONLY">
<MATCHING_FILE NAME="kernel32.dll" SIZE="993792" CHECKSUM="0xEA0DD182" BIN_FILE_VERSION="5.1.2600.7682" BIN_PRODUCT_VERSION="5.1.2600.7682" PRODUCT_VERSION="5.1.2600.7682" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="5.1.2600.7682 (xpsp_sp3_qfe_escrow.190315-1905)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x100F52" LINKER_VERSION="0x50001" UPTO_BIN_FILE_VERSION="5.1.2600.7682" UPTO_BIN_PRODUCT_VERSION="5.1.2600.7682" LINK_DATE="03/19/2019 18:39:07" UPTO_LINK_DATE="03/19/2019 18:39:07" VER_LANGUAGE="English (United States) [0x409]" />
</EXE>
</DATABASE>

**Comment by kirb** [comment]
Known issue with 1.4.1 at the moment, see #37 for more info. Workaround is to use 1.4 for now. Will close this since it's already covered by that issue thread.
