### ISSUE TITLE
Detect and install XP Embedded service packs in Legacy Update setup

### ISSUE THREAD

**Issue by ohault** [kirb/LegacyUpdate#73]
Hello,

The only issues encounter are the followings : 

- "Windows Fundamentals For Legacy PCs" is seen as "Windows XP Embedded SP2" in LegacyUpdate
- the proposed SP3 is not the good one for WinFLP

After applying manually https://archive.org/details/WinFLPSP3, the OS is seen by LegacyUpdate as Windows XP Embedded SP3

**Comment by kirb** [comment]
FLP is indeed XP Embedded, it only identifies itself as FLP via the winver dialog. The OS identification you see on the site is based on what the [GetVersionEx()](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw) Windows API function provides - it only became possible to get the exact brand name variant starting with Vista, so "XP Embedded" is as good as we get without digging specifically into the branding dll.

What happens when you install the SP3 update via Windows Update? Did you enable POSReady updates? I'm actually not sure if that’s compatible with XP Embedded.

**Comment by makuhlmann** [comment]
> the proposed SP3 is not the good one for WinFLP

If the update was SP3 for Windows XP Embedded, then it was the correct update. The SP3 Updates for Windows XP Embedded and Windows FLP are identical and compatible with each other. They were originally released as one download on Microsoft's download site: https://web.archive.org/web/20120618143236/https://www.microsoft.com/en-us/download/details.aspx?id=3740

**Comment by kirb** [comment]
I think this is working correctly then. Didn't receive any further clarification from OP, so closing.

**Comment by ohault** [comment]
I have just checked with Windows Embedded for Point of Sales (1.0) and Legacy Update 1.6.2 still propose the classic Windows XP SP3 in place of the appropriate one for this embedded edition of Windows XP.
![image](https://user-images.githubusercontent.com/5320161/218262765-73fe8215-0a87-452d-a65d-ebfc415a5a78.png)

**Comment by kirb** [comment]
Ah that is a good point. The setup doesn’t differentiate XP Embedded, that should be fixed.

**Comment by ohault** [comment]
This is also the case here - 
![image](https://user-images.githubusercontent.com/5320161/218264082-e9d2c72c-8bfa-4f9c-b714-1803f6e5eb05.png)

**Comment by kirb** [comment]
This *may* be installing WEPOS SP3 despite it appearing otherwise. Clicking Details should give you the KB number you can compare (XP SP3 is KB936929, WEPOS SP3 is KB958255). If not I can add a case for that as well.

**Comment by ohault** [comment]
![image](https://user-images.githubusercontent.com/5320161/218265240-68f4c69b-68cd-4649-b2dd-2a43805c0cba.png)

**Comment by kirb** [comment]
Well that’s interesting then. Come to think of it, even if I did add WEPOS SP3 to the list of service packs it checks for, that may not improve much, because the Microsoft server itself is what is pushing XP SP3 to what it should realise is a WEPOS install. If you select to review other updates, is WEPOS SP3 listed there at all? And if you go to your update history and click the error icon, what is the error code?

**Comment by ohault** [comment]
WEPOS SP3 (KB958255) is not listed in the review others updates, meanwhile others update for Windows XP Embedded were listed and has been installed successfully via Legacy Update.

**Comment by kirb** [comment]
Very strange, I’ll have to install it sometime soonish and see if I can investigate further. There may be no easy workaround for the site offering the wrong update, but I can definitely fix Legacy Update setup.

**Comment by ohault** [comment]
![image](https://user-images.githubusercontent.com/5320161/218266850-25726641-ad84-4a7e-8fe2-eecbcf25faa1.png)

**Comment by renodr** [comment]
> Very strange, I’ll have to install it sometime soonish and see if I can investigate further. There may be no easy workaround for the site offering the wrong update, but I can definitely fix Legacy Update setup.

Hey kirb! I was looking for some random things to do over here since I love tinkering with this kind of stuff, and I came across this.

I did a bit of research and discovered that the Microsoft Update Catalog does not carry KB958255 anymore, nor does the Microsoft Download Center! If you have a way to upload the installer for SP3 to the LegacyUpdate website, I'd be happy to do a PR to check for Windows Embedded and download that file (unless you'd rather do that 😄 )

**Comment by acoul** [comment]
is this the [KB958255](https://archive.org/download/WinFLPSP3) you are looking for ?

**Comment by renodr** [comment]
I've gotten the installer updated to handle the different service pack.

An initial round of Windows Update went about as well as you can hope for an XP system which can't use later versions of .NET Framework. 😉 
![image](https://github.com/kirb/LegacyUpdate/assets/11901488/b9e36242-0db4-4327-8be7-2c02e126d357)

After another round of Windows Update to confirm that no other updates are available, I will revert my snapshot and then try again with POSReady 2009 updates turned on. We'll then know if WEPOS can accept those from there, and then I will test on Fundamentals for Legacy PCs to make sure the service pack is fixed properly over there too.

**Comment by renodr** [comment]
Note that installing Windows Search 4.0 on WEPOS results in the search indexer crashing pretty much immediately. At least it brings up a Dr. Watson dump!

**Comment by renodr** [comment]
After a complete run of Windows Update (without POSReady 2009 updates turned on), the only two updates left are .NET Framework 3.5 Service Pack 1, and .NET Framework 4. It looks like WEPOS can't apply those because of missing OS components.

**Comment by renodr** [comment]
POSReady 2009 updates being enabled seems to have no effect, other than making the text at the bottom of the screen that would normally say "Windows Embedded Point of Service" say "Windows Embedded POSReady 2009". Note that WinVer does still identify it as Windows XP Embedded though.

![image](https://github.com/kirb/LegacyUpdate/assets/11901488/7e042dc5-a6fa-4e36-a29c-e9b3479ab1f3)

Off to test Fundamentals for Legacy PCs next!

**Comment by renodr** [comment]
With the PR I'm about to submit, FLP works properly as well and installs the correct service pack.

When it comes to running Windows Update, FLP accepts and uses POSReady2009 updates properly, and WEPOS will include select updates that are applicable to the limited components that it carries.

Also tested POSReady 2009 to make sure that I didn't break anything there

**Comment by greg-kennedy** [comment]
I just tried a from-scratch install of POSReady 2009 and then Legacy Update.  The top update is an "install separately" item, called Microsoft .NET Framework 4 Client Profile for Windows XP x86 (KB982670).  This downloaded fine but failed to install.

The logs show that I was missing an important Windows component as a prerequisite: it's "Windows Imaging Component", you can find it on archive.org here: https://archive.org/details/wic_x86_enu

After installing this (which, I think, XP SP3 comes with but Embedded does not), then the .NET installation is successful.

Just thought to share my experience here in case anyone else runs into trouble.

**Comment by sal-ammoniac** [comment]
> After a complete run of Windows Update (without POSReady 2009 updates turned on), the only two updates left are .NET Framework 3.5 Service Pack 1, and .NET Framework 4. It looks like WEPOS can't apply those because of missing OS components.

That is because WEPOS has a higher version oo wmphoto.dll,causing the installation of net 3.5 unable to proceed. Delete or rename it will help.
