### ISSUE TITLE
Windows Vista SP2 Internet Explorer 8 and Windows Update Errors

### ISSUE THREAD

**Issue by 7dog123** [kirb/LegacyUpdate#76]
When using Legacy update on Internet Explorer 8 it throws up 80072F78: The server response could not be parsed.

![Legecy update browser](https://user-images.githubusercontent.com/29476119/209899633-0f3bc378-d511-4f1e-9650-78f4ec5ce748.jpg)

and when using Windows Update it throws up 80072EFE: The connection with the server has been terminated. (Note: This error is common when the Windows Update Agent is out of date. Refer to the Legacy Update homepage for solutions.) When checking for Microsoft Update while it works with the Windows Update Portion.

![Windows update](https://user-images.githubusercontent.com/29476119/209900221-0e31c51d-e89e-479c-bcca-31c438f3f64b.jpg)

**Comment by kirb** [comment]
Closing because this is from quite a while ago, I think the issue may have been fixed if it was on our end. If not, feel free to reopen or file a new issue.
