### ISSUE TITLE
ActiveX Error?

### ISSUE THREAD

**Issue by PanMannYT** [kirb/LegacyUpdate#77]
Whenever i click Check Updates or View Log File, it says "The Legacy Update ActiveX control hasn't been installed. FOllow the instructions to install it.", doesnt say what type of OS im using, just says "Welcome. To use Legacy Update, follow the instructions below."

Even checking for updates does nothing, it keeps saying i dont have it installed, even if i have it installed and also have the ActiveX protocol thing installed and enabled in IE 6

I'm using RTM Windows XP updated to SP2.

**Comment by PanMannYT** [comment]
I tried both 1.4 and 1.4.1

**Comment by kirb** [comment]
Is this XP x64 Edition by any chance? Try visiting the website via Internet Explorer (32-bit) in the Start menu. There was a bug where it would sometimes wrongly launch 64-bit IE, fixed in 1.5, although now there’s another bug (#88) which I’m working on.

**Comment by PanMannYT** [comment]
I'm using Windows XP x32 bit.

**Comment by PanMannYT** [comment]
Has the issue been resolved in the latest release or the problem is still being investigated from where it is originated?

**Comment by PanMannYT** [comment]
It actualyl works now with the 1.6.1 release

**Comment by PanMannYT** [comment]
![image](https://user-images.githubusercontent.com/104730443/214264322-ba7aeae0-a24c-4bdd-ab90-ce8fded4f714.png)
actually, idrk about it working, it just checked for updates and shows me this

**Comment by kirb** [comment]
:raised_eyebrow: I'm stumped by how that could happen. Just in case, can you try removing `?firstrun=true`?

**Comment by PanMannYT** [comment]
> 

Where do i find that?

**Comment by kirb** [comment]
That was in the address bar in your screenshot, but you can also just launch Legacy Update again from the Start menu/Control Panel to get the “normal” non-first run version if you’ve already closed it.

**Comment by PanMannYT** [comment]
![image](https://user-images.githubusercontent.com/104730443/214286309-c53c158b-b233-4e96-8a40-34e6ea80ff4e.png)
nope, same results.

**Comment by kirb** [comment]
Could you give 1.6.2 a try? I refactored the way the dll is implemented, it may or may not make a difference. I also made the installer show you the error message if there's a problem registering the dll.

**Comment by PanMannYT** [comment]
![image](https://user-images.githubusercontent.com/104730443/214501711-12bd68bd-c04a-4d62-b1ae-3bc429bb62aa.png)
No errors have appeared, but unfortunately, nothing changed.

Is it a problem with the service unable to work with RTM installations?

**Comment by PanMannYT** [comment]
![image](https://user-images.githubusercontent.com/104730443/214501881-c74c3bc6-e3a8-40fc-8d4d-33b929643aa0.png)
Heres also what it shows before clicking on Review and install updates

**Comment by kirb** [comment]
It should be working on XP RTM, but let me try it myself and see what happens. 

Could you try letting it get to the screen in your screenshot, then press refresh/F5 (**don’t** hold down Ctrl - we want to have it do a reload from your local cache). Since the latest changes I made on the server, it’s been a bit inconsistent whether it works on the first load or not.

**Comment by PanMannYT** [comment]
I can't do it right now since I'm going to college, I'll try it later once I return home

**Comment by kirb** [comment]
No worries. Trying myself on RTM, first load I got this:

<details>

![XP RTM-2023-01-25-18-24-53](https://user-images.githubusercontent.com/773309/214509368-28382bf4-79b7-40ab-849b-717d1ddfccf5.png)
</details>

After refresh:

<details>

![XP RTM-2023-01-25-18-25-44](https://user-images.githubusercontent.com/773309/214509374-a08a97fb-260e-4e81-9596-b4405155b111.png)
</details>

After installing and restarting:

<details>

![XP RTM-2023-01-25-18-26-25](https://user-images.githubusercontent.com/773309/214509377-ade1e1ae-3fc8-419c-bb89-667fcafa1f6c.png)
</details>

Ick, that last one seems to be a different issue.

**Comment by PanMannYT** [comment]
I unfortunately cannot see the images since I'm using a iPhone 3GS as my daily driver, but hopefully you figure out how to fix the issues you encountered on your attempt.

Sent from my iPhone

**Comment by PanMannYT** [comment]
> 

Try updating the installation to SP2

**Comment by PanMannYT** [comment]
It works now, thanks!
