### ISSUE TITLE
Legacy Update - Windows Server 2008 R2 SP1 Standard - IE 11

### ISSUE THREAD

**Issue by Annunaki** [kirb/LegacyUpdate#78]
So after a bit of a wobble after installing Legacy Update [https://github.com/kirb/LegacyUpdate/issues/51](url) the updates eventually came through via the default shipped IE however after the 1st wave of updates Internet Explorer 11 got installed then after when opening Legacy Update I am faced with a partially blank website, The left navigation section is there, but the main part of the site is blank.

I noticed updates eventually started downloading in the background and when they had finished I clicked to view the updates as prompted to be taken to the Windows Update GUI which asked me to scan for updates.... After manually scanning for updates, the list eventually got populated, and I was able to continue updating from the default Windows Update GUI (Legacy Update website remains bugged on IE 11)

**Comment by 7dog123** [comment]
It's been explained in Issue https://github.com/kirb/LegacyUpdate/issues/19#issuecomment-1327059522

**Comment by kirb** [comment]
Addressed this as explained in https://github.com/kirb/LegacyUpdate/issues/19#issuecomment-1379973880
