### ISSUE TITLE
Crashing on ThinkPad R30

### ISSUE THREAD

**Issue by AstaFatherSatan** [kirb/LegacyUpdate#86]
As the title says
Steps to reproduce the issue;
- Clean install of XP SP3 x86
- Update using legacyupdate then reboot after installation of all the updates.

**Comment by AstaFatherSatan** [comment]
![IMG_20230109_183924](https://user-images.githubusercontent.com/94870997/211429790-e865b5a9-22a4-46bd-9bf1-33b54cf38be1.jpg)
![IMG_20230109_183946](https://user-images.githubusercontent.com/94870997/211429793-6dfbfa0b-1faf-4bed-a47c-6d3f442f6248.jpg)

**Comment by AstaFatherSatan** [comment]
![IMG_20230109_184053](https://user-images.githubusercontent.com/94870997/211429902-ee1f6ff1-92fd-46d9-b878-9d637f4ad32b.jpg)

**Comment by AstaFatherSatan** [comment]
I forgot to mention i downgraded ie8 to ie6 as it was crashing there too. Same error.

**Comment by AstaFatherSatan** [comment]
I found the problematic update. The number ended in 022. After removing said update it's working again.

**Comment by AstaFatherSatan** [comment]
Update; Winlogin.exe is crashing because sfc_os.dll was not found followed by a bluescreen. This could of been caused by removing updates until I found the one that caused the issue.

**Comment by lichtmetzger** [comment]
Possibly related: Some late updates for Windows XP (POSReady 2009) and Office 2010 silently required SSE2 instruction support. The ThinkPad R30's CPU does not support these instructions so these updates break the system.

https://www.vogons.org/viewtopic.php?t=62235

According to that thread, KB4495**022** is known to fail. Maybe that's the update you encountered.

**Comment by kirb** [comment]
Indeed I think this is because of SSE2 updates being installed on a non-SSE2 CPU. I'd say best if you disable POSReady updates for now (run regedit, go to `HKEY_LOCAL_MACHINE\System\WPA\POSReady`, delete `Installed`, and reboot). I opened #89 to encapsulate the discussion going forward, so will close this in favor of that.
