### ISSUE TITLE
XP SP3 x86 "The parameter is incorrect"

### ISSUE THREAD

**Issue by david-goliath93** [kirb/LegacyUpdate#88]
Specs are i7-4790k with GA-Q87M-D2H and a Radeon HD7950. No matter what, LegacyUpdate just errors out with "The parameter is incorrect". Will boot to XP and attach screenshot in a little

**Comment by CaelThunderwing** [comment]
just installed this on a Project system i got Kludged together ( manage dto get XP SP2 w/ an update to SP3) to install on a Mac Mini  (mid 2010 Unibody [MacMini4,1])
it's doing the same here and going directly to LU and trying to check for updates results in 80072EFE

**Comment by david-goliath93** [comment]
![image](https://user-images.githubusercontent.com/122513193/212011477-b8ad9cc7-6b04-4d47-8862-1b7bf96e62db.png)

**Comment by DaddyBurrito** [comment]
Hi, I just installed Legacy Update on a Dell PowerEdge 500SC computer that I installed the OEM version of Windows XP SP3 on. It seems to be working perfectly and other software I have installed seems to be good but LegacyUpdate produces "The parameter is incorrect" error when I click on it from the Windows XP Start menu. Checking the about information it shows that I installed version 1.5. What can I do to fix the issue and get this working correctly. Thank you again for the support and advice.

**Comment by stdin82** [comment]
@kirb Maybe Windows x86 did not like the `CLSCTX_ACTIVATE_32_BIT_SERVER` addition to CoCreateInstance

it's possible instead to modify setup.nsi and change `rundll32.exe` commands to be executed from `C:\Windows\SysWOW64` for Windows x64

i tested this manually with 1.4.1 and works

**Comment by renodr** [comment]
That's definitely possible! Alternatively, how about if we do a check to only add the CLSCTX_ACTIVATE_32_BIT_SERVER on 64-bit XP/Server 2003? Newer versions don't require it since they default to starting it on 32-bit mode to begin with

I'd be happy to prepare a patch for this 😃

**Comment by kirb** [comment]
That sounds like the right call, since the shortcut we install can of course be changed, but I'd be concerned if the user has made other copies of the shortcut that we can't easily change. Would be glad to see a PR if you're interested :slightly_smiling_face:

**Comment by renodr** [comment]
> That sounds like the right call, since the shortcut we install can of course be changed, but I'd be concerned if the user has made other copies of the shortcut that we can't easily change. Would be glad to see a PR if you're interested 🙂

I agree! I'll have a PR in soon. 😃

**Comment by ThePizzaHair** [comment]
i have same issue on Windows 2000 SP4

`@"C:\Program Files\Legacy Update\LegacyUpdate.dll",-4` this gives me a error
![image](https://user-images.githubusercontent.com/91389614/212543719-39a58055-2cfa-4f2e-9aa2-b5bcaa64f494.png)

**Comment by renodr** [comment]
> i have same issue on Windows 2000 SP4
> 
> `@"C:\Program Files\Legacy Update\LegacyUpdate.dll",-4` this gives me a error ![image](https://user-images.githubusercontent.com/91389614/212543719-39a58055-2cfa-4f2e-9aa2-b5bcaa64f494.png) _sorry for 16 color resolution_

That makes sense, I think its due to the CLSCTX flag not being supported over there too 😃 

I'll test my PR on 2000 Pro as well!

**Comment by DellM-79** [comment]
I handled the issue myself. Will it fix Legacy Update on XP?? I hope so.

**Comment by renodr** [comment]
> That sounds like the right call, since the shortcut we install can of course be changed, but I'd be concerned if the user has made other copies of the shortcut that we can't easily change. Would be glad to see a PR if you're interested 🙂

PR #94 :smiley:

**Comment by ccgfok** [comment]
Tested on winxp on vm, tested that the ver 1.5 shows "The parameters is incorrect" so its stoped working.
![Windows XP Professional-2023-01-18-02-16-25](https://user-images.githubusercontent.com/11695493/212967148-292686bd-b1b4-48ac-b072-66568d2febc4.png)

**Comment by 4pack** [comment]
Can also confirm, same parameter incorrect with Windows 2000 Advanced Server.
![image](https://user-images.githubusercontent.com/3211393/213008695-3ee34523-7d10-4c77-85ef-c97c437e5a6e.png)

**Comment by kirb** [comment]
Fixed in 1.6, thanks @renodr and everyone else who chimed in on this thread :slightly_smiling_face:
