### ISSUE TITLE
Windows Update Agent doesn't get updated when installing Legacy Update

### ISSUE THREAD

**Issue by RUvlad1** [kirb/LegacyUpdate#90]
For some reason WUA doesn't get updated, also when the installation finishes and the OS gets restarted, usually the system should log in to a temporary account where Legacy Update continues the installation, that did not happen and I was logged in back to my Administrator account

![image](https://user-images.githubusercontent.com/60317461/212169612-bfde5715-597d-433d-99d9-3fd35f2183e5.png)
![image](https://user-images.githubusercontent.com/60317461/212169657-48badef6-4e0a-4f5a-ba3f-d9c27f4ebb48.png)

Also it tells me to the homepage for solution, but I couldn't find anything that would help me
i might be blind so in that case im sorry :((

My OS is Windows XP x64 SP2

**Comment by CaelThunderwing** [comment]
try using 1.4.1 to get this delt with, occured for my case and 1.4.1 fixed it.

**Comment by Crazzzme** [comment]
I am having this same issue on Vista

**Comment by kirb** [comment]
There was an issue with Legacy Update 1.5 causing the update server registry keys to not be configured correctly. This has been fixed in 1.6, thanks for reporting.
