### ISSUE TITLE
problem with installing on Windows XP

### ISSUE THREAD

**Issue by whistl353** [kirb/LegacyUpdate#91]
i tried to install Legacy Update 1.5 on Windows XP Pro SP3, but it didn't work and it show me an error.

**Comment by mina354** [comment]
Does it crash when you open setup? Because that's what happened for me (yes, even with version 1.5!):
![image](https://user-images.githubusercontent.com/87821255/212486889-52e2f5a1-4123-4c74-bdd4-5fbbe91c2a65.png)

**Comment by whistl353** [comment]
yes

**Comment by kirb** [comment]
Which XP edition (Pro, Home, etc) and service pack are you running on?

**Comment by MatzeGaming558** [comment]
I have the same problem. I am running Win XP Home SP3.

**Comment by whistl353** [comment]
Windows XP Pro SP3. I have been writen that at the start of issue.

**Comment by whistl353** [comment]
https://github.com/kirb/LegacyUpdate/issues/91#issue-1533306676 there

**Comment by yotoprules** [comment]
I have the same problem with 1.4.1 and 1.5, whereas 1.4 works fine.

**Comment by whistl353** [comment]
yep, tried to install from Github by Mypal bc ie 6 didn't work with github

**Comment by andutrache** [comment]
tried 1.5 on Windows XP Professional SP3 and I either get a crash or a box with "The parameter is incorrect."

**Comment by Skywatcher17** [comment]
Same problem here.

**Comment by vertaa** [comment]
I running into a similiar error. Have to install it a few times for it to finish, but I still get this error. normal install

![image](https://user-images.githubusercontent.com/67488797/213069459-e9144f2b-d04e-48c9-89c2-8054e0e71c00.png)

on Windows XP Professional SP3 x86 - Integral Edition 2022.9.9 the installer will not run.

**Comment by kirb** [comment]
Thanks everyone for heling out in this thread, really appreciate it. This should be fixed in 1.6.
