### ISSUE TITLE
not functioning on windows 2000

### ISSUE THREAD

**Issue by staticanimal** [kirb/LegacyUpdate#95]
version 1.5 installs but when launching legacy update from the start menu i get an error that just says "the parameter is incorrect".
manually navigating to legacyupdate.net threw some kind of error about something being disconnected from a server immediately after which all legacy update functionality vanished from the windows install with the website reporting that legacy update isn't installed whatsoever and launching the legacy update installer immediately erroring out with "the parameter is incorrect" again.

[version 1.4.1 seems to have none of these issues]

**Comment by renodr** [comment]
This should be fixed once the next version of LegacyUpdate is released 😃 I fixed it in PR #94

**Comment by kirb** [comment]
You can still directly go to http://legacyupdate.net in Internet Explorer as a workaround, by the way. The shortcut is just a convenient link directly to the site.

**Comment by stdin82** [comment]
version 1.5 also don't set `UseWUServer` registry, so unless you have older version installed or added the value yourself, v1.5 won't work
