### ISSUE TITLE
Error in Website

### ISSUE THREAD

**Issue by guest123guest** [kirb/LegacyUpdate#97]
The following quote is wrong:

> You should stick to a supported OS such as Windows 10 or 11 (or, try Linux?!)

Windows 10 and 11 are completely insecure due to fundamental flaws within the Windows NT kernel that can't be fixed without a complete rewrite, even if they are still "supported" by Microshaft. You should change it and all mentions of Windows 10 and 11 to endorse switching to a Linux distribution, a BSD, FreeDOS, or http://www.pdos.org/.

**Comment by lichtmetzger** [comment]
> Windows 10 and 11 are completely insecure due to fundamental flaws within the Windows NT kernel that can't be fixed without a complete rewrite

Do you have any factual proof for that?

**Comment by kirb** [comment]
No.

**Comment by llsc12** [comment]
this would make for a good copypasta lmao

**Comment by Absolucy** [comment]
![Senator Armstrong from Metal Gear Rising saying "My source is that I made it the fuck up"](https://media.tenor.com/v6Awsd0YO7IAAAAC/metal-gear-rising-metal-gear-rising-revengeance.gif)
