### ISSUE TITLE
v1.6 unknown bug

### ISSUE THREAD

**Issue by XPMilkChan** [kirb/LegacyUpdate#98]
I tested v1.6 in another language (Japanese), very strange to get unknown error.
![bandicam 2023-01-19 10-33-09-171](https://user-images.githubusercontent.com/106049626/213349736-867ac9fe-f6e6-4d01-831b-d1bca56bafe2.jpg)

**Comment by kirb** [comment]
I was just messing with the site, it might be fixed now. Can you try Ctrl-F5?

**Comment by XPMilkChan** [comment]
> I was just messing with the site, it might be fixed now. Can you try Ctrl-F5?

OK
![bandicam 2023-01-19 11-34-30-993](https://user-images.githubusercontent.com/106049626/213355943-b26641b1-e300-4dd5-994d-25b4dbd2a54c.jpg)
